name: Generate pacman animation

on:
  schedule:
    # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Prepare dist folder
        run: |
          mkdir -p dist
          echo "Checking generated files..."
          if [ -f pacman-contribution-graph.svg ]; then
            mv pacman-contribution-graph.svg dist/
            echo "Moved pacman-contribution-graph.svg"
          else
            echo "pacman-contribution-graph.svg not found"
          fi
          if [ -f pacman-contribution-graph-dark.svg ]; then
            mv pacman-contribution-graph-dark.svg dist/
            echo "Moved pacman-contribution-graph-dark.svg"
          else
            echo "pacman-contribution-graph-dark.svg not found"
          fi
          echo "Dist folder content:"
          ls -la dist

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
